apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: marklogic-load-test-
  namespace: ml
spec:
  entrypoint: marklogic-load-test-pipeline
  serviceAccountName: argo-workflow
  
  arguments:
    parameters:
    - name: marklogic-endpoint
      value: "http://ml12-cluster.ml.svc.cluster.local:8000"
    - name: marklogic-database
      value: "Documents"
    - name: batch-size
      value: "10"
    - name: parallelism
      value: "4"
    - name: insecure-skip-tls-verify
      value: "false"
    - name: base-path
      value: ""
  
  templates:
  - name: marklogic-load-test-pipeline
    steps:
    - - name: deploy-test-config
        template: deploy-k6-config
    
    - - name: run-load-test
        template: execute-k6-loadtest
    
    - - name: wait-for-completion
        template: wait-test-completion
    
    - - name: get-test-results
        template: fetch-results
    
    - - name: cleanup
        template: cleanup-resources

  - name: deploy-k6-config
    resource:
      action: apply
      manifest: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: marklogic-load-test-script
          namespace: ml
        data:
          marklogic-load-test.js: |
            import http from 'k6/http';
            import { check, sleep } from 'k6';
            import { randomString, randomIntBetween } from 'k6/experimental/rand';

            const generateRandomDocument = () => {
              return JSON.stringify({
                id: `${Date.now()}-${randomIntBetween(1, 1000000)}`,
                first_name: randomString(8),
                last_name: randomString(10),
                email: `${randomString(8)}@example.com`,
                ip_address: `${randomIntBetween(1, 255)}.${randomIntBetween(1, 255)}.${randomIntBetween(1, 255)}.${randomIntBetween(1, 255)}`,
                city: randomString(10),
                state: randomString(2).toUpperCase(),
                postal_code: `${randomIntBetween(10000, 99999)}`,
                country: randomString(12),
                phone_number: `${randomIntBetween(100, 999)}-${randomIntBetween(100, 999)}-${randomIntBetween(1000, 9999)}`
              });
            };

            export const options = {
              stages: [
                { duration: '30s', target: 10 },
                { duration: '1m', target: 10 },
                { duration: '30s', target: 20 },
                { duration: '1m', target: 20 },
                { duration: '30s', target: 0 },
              ],
              thresholds: {
                http_req_failed: ['rate<0.01'],
                http_req_duration: ['p(95)<5000'],
                'http_req_duration{operation:write}': ['p(95)<3000'],
              },
              insecureSkipTLSVerify: __ENV.INSECURE_SKIP_TLS_VERIFY === 'true',
            };

            export default function () {
              const MARKLOGIC_ENDPOINT = __ENV.MARKLOGIC_ENDPOINT || 'http://ml12-cluster.ml.svc.cluster.local:8000';
              const MARKLOGIC_USER = __ENV.MARKLOGIC_USER || 'admin';
              const MARKLOGIC_PASSWORD = __ENV.MARKLOGIC_PASSWORD || 'admin';
              const MARKLOGIC_DATABASE = __ENV.MARKLOGIC_DATABASE || 'Documents';
              const BATCH_SIZE = parseInt(__ENV.BATCH_SIZE || '10');
              const BASE_PATH = __ENV.BASE_PATH || '';

              const batch = [];
              for (let i = 0; i < BATCH_SIZE; i++) {
                batch.push(generateRandomDocument());
              }

              const documents = batch.map((doc, index) => {
                const uri = `/test/row/${Date.now()}-${index}.json`;
                return { uri: uri, content: doc };
              });

              const payload = JSON.stringify({ documents: documents });

              const params = {
                headers: {
                  'Content-Type': 'application/json',
                  'Authorization': `Basic ${__ENV.MARKLOGIC_AUTH || btoa(`${MARKLOGIC_USER}:${MARKLOGIC_PASSWORD}`)}`,
                },
                tags: { operation: 'write' },
                timeout: '10s',
              };

              const writeUrl = `${MARKLOGIC_ENDPOINT}${BASE_PATH}/v1/documents?database=${MARKLOGIC_DATABASE}`;
              const writeRes = http.post(writeUrl, payload, params);

              check(writeRes, {
                'write successful': (r) => r.status === 200 || r.status === 204,
                'write response time ok': (r) => r.timings.duration < 5000,
              });

              const queryUrl = `${MARKLOGIC_ENDPOINT}${BASE_PATH}/v1/search?database=${MARKLOGIC_DATABASE}&q=*&pageLength=10`;
              const queryRes = http.get(queryUrl, {
                headers: {
                  'Accept': 'application/json',
                  'Authorization': params.headers.Authorization,
                },
                tags: { operation: 'read' },
                timeout: '5s',
              });

              check(queryRes, {
                'query successful': (r) => r.status === 200,
                'query response time ok': (r) => r.timings.duration < 2000,
              });

              sleep(1);
            }

  - name: execute-k6-loadtest
    resource:
      action: apply
      manifest: |
        apiVersion: k6.io/v1alpha1
        kind: TestRun
        metadata:
          name: marklogic-load-test-{{workflow.uid}}
          namespace: ml
        spec:
          parallelism: {{workflow.parameters.parallelism}}
          script:
            configMap:
              name: marklogic-load-test-script
              file: marklogic-load-test.js
          runner:
            image: grafana/k6:latest
            env:
            - name: MARKLOGIC_ENDPOINT
              value: "{{workflow.parameters.marklogic-endpoint}}"
            - name: MARKLOGIC_DATABASE
              value: "{{workflow.parameters.marklogic-database}}"
            - name: BATCH_SIZE
              value: "{{workflow.parameters.batch-size}}"
            - name: INSECURE_SKIP_TLS_VERIFY
              value: "{{workflow.parameters.insecure-skip-tls-verify}}"
            - name: BASE_PATH
              value: "{{workflow.parameters.base-path}}"
            - name: MARKLOGIC_USER
              valueFrom:
                secretKeyRef:
                  name: marklogic-admin-secret
                  key: username
                  optional: true
            - name: MARKLOGIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: marklogic-admin-secret
                  key: password
                  optional: true
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
          separate: false

  - name: wait-test-completion
    script:
      image: bitnami/kubectl:latest
      command: [bash]
      source: |
        #!/bin/bash
        set -e
        
        TESTRUN_NAME="marklogic-load-test-{{workflow.uid}}"
        NAMESPACE="ml"
        TIMEOUT=600
        ELAPSED=0
        
        echo "Waiting for load test ${TESTRUN_NAME} to complete..."
        
        while [ $ELAPSED -lt $TIMEOUT ]; do
          STATUS=$(kubectl get testrun ${TESTRUN_NAME} -n ${NAMESPACE} -o jsonpath='{.status.stage}' 2>/dev/null || echo "not-found")
          
          echo "Current status: ${STATUS}"
          
          if [ "$STATUS" == "finished" ] || [ "$STATUS" == "error" ]; then
            echo "Load test completed with status: ${STATUS}"
            
            if [ "$STATUS" == "error" ]; then
              echo "Load test failed!"
              exit 1
            fi
            
            exit 0
          fi
          
          sleep 10
          ELAPSED=$((ELAPSED + 10))
        done
        
        echo "Timeout waiting for load test to complete"
        exit 1

  - name: fetch-results
    script:
      image: bitnami/kubectl:latest
      command: [bash]
      source: |
        #!/bin/bash
        set -e
        
        TESTRUN_NAME="marklogic-load-test-{{workflow.uid}}"
        NAMESPACE="ml"
        
        echo "========================================="
        echo "K6 Load Test Results for MarkLogic"
        echo "========================================="
        
        echo ""
        echo "TestRun Status:"
        kubectl get testrun ${TESTRUN_NAME} -n ${NAMESPACE} -o yaml
        
        echo ""
        echo "========================================="
        echo "Load Test Logs:"
        echo "========================================="
        
        kubectl logs -n ${NAMESPACE} -l k6_cr=${TESTRUN_NAME} --tail=200 || echo "No logs found"
        
        echo ""
        echo "========================================="
        echo "Performance Summary:"
        echo "========================================="
        kubectl logs -n ${NAMESPACE} -l k6_cr=${TESTRUN_NAME} --tail=50 | grep -E "http_req|check" || true

  - name: cleanup-resources
    script:
      image: bitnami/kubectl:latest
      command: [bash]
      source: |
        #!/bin/bash
        
        TESTRUN_NAME="marklogic-load-test-{{workflow.uid}}"
        NAMESPACE="ml"
        
        echo "Cleaning up load test resources..."
        
        kubectl delete testrun ${TESTRUN_NAME} -n ${NAMESPACE} --ignore-not-found=true
        
        echo "Cleanup complete"
