apiVersion: v1
kind: ConfigMap
metadata:
  name: marklogic-load-test-script
  namespace: ml
data:
  marklogic-load-test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';
    import { randomString, randomIntBetween } from 'k6/experimental/rand';

    // Generate random document similar to marklogic-data-storm
    const generateRandomDocument = () => {
      return JSON.stringify({
        id: `${Date.now()}-${randomIntBetween(1, 1000000)}`,
        first_name: randomString(8),
        last_name: randomString(10),
        email: `${randomString(8)}@example.com`,
        ip_address: `${randomIntBetween(1, 255)}.${randomIntBetween(1, 255)}.${randomIntBetween(1, 255)}.${randomIntBetween(1, 255)}`,
        city: randomString(10),
        state: randomString(2).toUpperCase(),
        postal_code: `${randomIntBetween(10000, 99999)}`,
        country: randomString(12),
        phone_number: `${randomIntBetween(100, 999)}-${randomIntBetween(100, 999)}-${randomIntBetween(1000, 9999)}`
      });
    };

    export const options = {
      stages: [
        { duration: '30s', target: 10 },
        { duration: '1m', target: 10 },
        { duration: '30s', target: 20 },
        { duration: '1m', target: 20 },
        { duration: '30s', target: 0 },
      ],
      thresholds: {
        http_req_failed: ['rate<0.01'],
        http_req_duration: ['p(95)<5000'],
        'http_req_duration{operation:write}': ['p(95)<3000'],
      },
    };

    export default function () {
      const MARKLOGIC_ENDPOINT = __ENV.MARKLOGIC_ENDPOINT || 'http://ml12-cluster.ml.svc.cluster.local:8000';
      const MARKLOGIC_USER = __ENV.MARKLOGIC_USER || 'admin';
      const MARKLOGIC_PASSWORD = __ENV.MARKLOGIC_PASSWORD || 'admin';
      const MARKLOGIC_DATABASE = __ENV.MARKLOGIC_DATABASE || 'Documents';
      const BATCH_SIZE = parseInt(__ENV.BATCH_SIZE || '10');

      // Create batch of documents
      const batch = [];
      for (let i = 0; i < BATCH_SIZE; i++) {
        batch.push(generateRandomDocument());
      }

      // Prepare documents for bulk write
      const documents = batch.map((doc, index) => {
        const uri = `/test/row/${Date.now()}-${index}.json`;
        return { uri: uri, content: doc };
      });

      const payload = JSON.stringify({ documents: documents });

      const params = {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Basic ${__ENV.MARKLOGIC_AUTH || btoa(`${MARKLOGIC_USER}:${MARKLOGIC_PASSWORD}`)}`,
        },
        tags: { operation: 'write' },
        timeout: '10s',
      };

      // Write to MarkLogic with database parameter
      const writeUrl = `${MARKLOGIC_ENDPOINT}/v1/documents?database=${MARKLOGIC_DATABASE}`;
      const writeRes = http.post(writeUrl, payload, params);

      check(writeRes, {
        'write successful': (r) => r.status === 200 || r.status === 204,
        'write response time ok': (r) => r.timings.duration < 5000,
      });

      // Optional read test with database parameter
      const queryUrl = `${MARKLOGIC_ENDPOINT}/v1/search?database=${MARKLOGIC_DATABASE}&q=*&pageLength=10`;
      const queryRes = http.get(queryUrl, {
        headers: {
          'Accept': 'application/json',
          'Authorization': params.headers.Authorization,
        },
        tags: { operation: 'read' },
        timeout: '5s',
      });

      check(queryRes, {
        'query successful': (r) => r.status === 200,
        'query response time ok': (r) => r.timings.duration < 2000,
      });

      sleep(1);
    }
---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: marklogic-load-test
  namespace: ml
spec:
  parallelism: 4
  script:
    configMap:
      name: marklogic-load-test-script
      file: marklogic-load-test.js
  runner:
    image: grafana/k6:latest
    env:
    - name: MARKLOGIC_ENDPOINT
      value: "http://ml12-cluster.ml.svc.cluster.local:8000"
    - name: MARKLOGIC_DATABASE
      value: "Documents"
    - name: MARKLOGIC_USER
      valueFrom:
        secretKeyRef:
          name: marklogic-admin-secret
          key: username
          optional: true
    - name: MARKLOGIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: marklogic-admin-secret
          key: password
          optional: true
    - name: BATCH_SIZE
      value: "10"
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  separate: false
