apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: marklogic-data-storm-faker-inline-thirty
  namespace: ml
  labels:
    app: k6-load-test
    test-type: marklogic-faker-inline-thirty
spec:
  parallelism: 10
  
  # Reference to the ConfigMap containing the k6 script
  script:
    configMap:
      name: marklogic-data-storm-faker-inline-script
      file: marklogic-data-storm-faker-inline.js
  
  # Runner configuration
  runner:
    image: grafana/k6:latest
    
    # Environment variables for MarkLogic connection and test configuration
    env:
      # Prometheus Remote Write configuration for k6 test metrics
      - name: K6_OUT
        value: "experimental-prometheus-rw"
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: "http://rancher-monitoring-prometheus.cattle-monitoring-system.svc.cluster.local:9090/api/v1/write"
      - name: K6_PROMETHEUS_RW_TREND_STATS
        value: "p(50),p(90),p(95),p(99),min,max,avg,med,count"
      - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
        value: "5s"
      - name: K6_TAG_TESTID
        value: "marklogic-data-storm-faker-inline-thirty"
      # MarkLogic Connection Settings
      - name: ML_HOST
        value: "marklogic-haproxy.ml.svc.cluster.local"
      - name: ML_PORT
        value: "443"
      - name: ML_USER
        valueFrom:
          secretKeyRef:
            name: ml1
            key: username
      - name: ML_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ml1
            key: password
      - name: ML_DATABASE
        value: "Documents"
      - name: ML_AUTH_TYPE
        value: "basic"
      - name: ML_PROTOCOL
        value: "http"
      # Base path for load balancer routing (e.g., '/marklogic' if LB routes /marklogic/* to MarkLogic)
      # Leave empty or remove if MarkLogic is accessed directly without a path prefix
      - name: ML_BASE_PATH
        value: "/console"
      - name: ML_URI_PREFIX
        value: "/k6-faker-inline-test/"
      - name: ML_COLLECTIONS
        value: "k6-faker-inline-test,load-test"
      
      # Document Generation Settings
      # Supported types: standard, minimal, extended, financial, ecommerce, healthcare, iot, social, log
      - name: DOC_TYPE
        value: "extended,person,financial,food,airline,book,ecommerce,healthcare,location,iot,social,log"
      - name: INCLUDE_DOC_METADATA
        value: "true"
      
      # Batch Processing Settings
      - name: BATCH_SIZE
        value: "2000"
      - name: SLEEP_DURATION
        value: "0.01"
      
      # Staging Configuration - Ramping burst every 1 minute
      # Format: "duration:target_vus,duration:target_vus,..."
      - name: K6_STAGES
        value: "2m:500,32m:500"
      
      # Alternative ramping configuration (uncomment to use instead of K6_STAGES)
      # - name: RAMP_UP_INTERVAL
      #   value: "2m"
      # - name: VU_INCREMENT
      #   value: "100"
      # - name: MAX_VUS
      #   value: "500"
      # - name: HOLD_DURATION
      #   value: "10m"
      
      # Test metadata
      - name: TEST_NAME
        value: "marklogic-faker-inline-burst"
      - name: ENVIRONMENT
        value: "development"
      
      # Debug mode (set to "true" to enable verbose logging)
      - name: DEBUG
        value: "false"
    
    # Resource limits
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "2000m"
        memory: "2Gi"
    
    # Node selector - schedule k6 runners on specific nodes
    nodeSelector:
      role: rwinieski-node
      # Add your custom node labels here, e.g.:
      # node-role.kubernetes.io/worker: "true"
      # workload-type: load-test
