apiVersion: v1
kind: ConfigMap
metadata:
  name: marklogic-health-check-script
  namespace: ml
data:
  marklogic-health-check.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export const options = {
      vus: 1,
      duration: '30s',
      thresholds: {
        http_req_failed: ['rate<0.1'], // http errors should be less than 10%
        http_req_duration: ['p(95)<2000'], // 95% of requests should be below 2s
      },
    };

    export default function () {
      // Test MarkLogic App Services endpoint (port 8000)
      const appServicesUrl = 'http://ml12-cluster.ml.svc.cluster.local:8000';
      
      const appServicesRes = http.get(appServicesUrl, {
        timeout: '10s',
      });

      check(appServicesRes, {
        'MarkLogic App Services is reachable': (r) => r.status === 200 || r.status === 401 || r.status === 302,
        'MarkLogic App Services response time < 2s': (r) => r.timings.duration < 2000,
      });

      // Test MarkLogic Admin UI endpoint (port 8001)
      const adminUrl = 'http://ml12-cluster.ml.svc.cluster.local:8001';
      
      const adminRes = http.get(adminUrl, {
        timeout: '10s',
      });

      check(adminRes, {
        'MarkLogic Admin UI is reachable': (r) => r.status === 200 || r.status === 401 || r.status === 302,
        'MarkLogic Admin UI response time < 2s': (r) => r.timings.duration < 2000,
      });

      // Test MarkLogic Manage endpoint (port 8002)
      const manageUrl = 'http://ml12-cluster.ml.svc.cluster.local:8002';
      
      const manageRes = http.get(manageUrl, {
        timeout: '10s',
      });

      check(manageRes, {
        'MarkLogic Manage API is reachable': (r) => r.status === 200 || r.status === 401 || r.status === 302,
        'MarkLogic Manage API response time < 2s': (r) => r.timings.duration < 2000,
      });

      console.log(`App Services Status: ${appServicesRes.status}, Admin UI Status: ${adminRes.status}, Manage API Status: ${manageRes.status}`);

      sleep(1);
    }
---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: marklogic-health-check
  namespace: ml
spec:
  parallelism: 1
  script:
    configMap:
      name: marklogic-health-check-script
      file: marklogic-health-check.js
  runner:
    image: grafana/k6:latest
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  separate: false
