apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: marklogic-data-storm-faker
  namespace: ml
spec:
  parallelism: 10
  script:
    configMap:
      name: marklogic-data-storm-faker-script
      file: marklogic-data-storm-faker.js
  runner:
    image: grafana/k6:latest
    env:
    # Prometheus Remote Write configuration for k6 test metrics
    - name: K6_OUT
      value: "experimental-prometheus-rw"
    - name: K6_PROMETHEUS_RW_SERVER_URL
      value: "http://rancher-monitoring-prometheus.cattle-monitoring-system.svc.cluster.local:9090/api/v1/write"
    - name: K6_PROMETHEUS_RW_TREND_STATS
      value: "p(50),p(90),p(95),p(99),min,max,avg,med,count"
    - name: K6_PROMETHEUS_RW_PUSH_INTERVAL
      value: "5s"
    - name: K6_TAG_TESTID
      value: "marklogic-data-storm-faker"
    
    # MarkLogic connection settings
    - name: HOST
      value: "dnode-0.dnode.ml.svc.cluster.local"
    - name: PORT
      value: "8000"
    - name: SSL
      value: "false"
    - name: BASE_PATH
      value: ""
    
    # Database and authentication
    - name: DATABASE
      value: "Documents"
    - name: USERNAME
      value: "ml-admin"
    - name: PASSWORD
      value: "ml-admin-2023"
    - name: AUTH_TYPE
      value: "basic"
    
    # Document generation settings
    # Available types: standard, minimal, extended, financial, ecommerce, healthcare, iot, social, log
    # Use comma-separated values for multiple types (randomly selected per document)
    - name: DOC_TYPE
      value: "standard,financial,ecommerce,healthcare"
    - name: INCLUDE_DOC_METADATA
      value: "true"
    
    # Load test configuration
    - name: BATCH_SIZE
      value: "3000"
    - name: THREAD_COUNT
      value: "320"
    - name: THINK_TIME
      value: "0.05"
    
    # Burst/Ramping configuration - increases VUs every 1 minute
    # Format: duration:target,duration:target,...
    - name: K6_STAGES
      value: "1m:100,1m:200,1m:300,1m:400,1m:500"
    
    # Alternative: Use scenarios for more control
    - name: RAMP_UP_INTERVAL
      value: "1m"
    - name: VU_INCREMENT
      value: "100"
    - name: MAX_VUS
      value: "500"
    
    # TLS settings
    - name: INSECURE_SKIP_TLS_VERIFY
      value: "false"
    
    # Optional REST transform
    # - name: REST_TRANSFORM
    #   value: ""
    
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  
  # Separate runner for each VU (optional, false means single pod)
  separate: false
  
  # Cleanup policy (delete pods after test completes)
  cleanup: "post"
